# Configuration informaton for the Synthetic application
# The app expects this file to be called {RAILS_ROOT}/config/dukeapps-creds.yml, so place it somewhere
# secure (such as /etc/) and then create a link from the app dir tree
# Information should not be packaged with the app in SVN for security reasons
# This file ideally should only be accessible by the application itself

# DEFAULT settings.  Override for specific instance below if necessary

defaults: &DEFAULTS
   test: testing

development:
  <<: *DEFAULTS

staging:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS

